name: Functional Tests

on: [pull_request]


jobs:
  test:
    env:
      CI: true
      _FORCE_LOGS: 1
      XCODE_VERSION: 13.4
      DEVICE_NAME: iPhone 11
      PLATFORM_VERSION: 15.5
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "${{ env.XCODE_VERSION }}"
    - run: |
        npm install
        mkdir -p ./Resources/WebDriverAgent.bundle
      name: Install dev dependencies

    - run: |
        target_sim_id=$(xcrun simctl list devices available | grep "$DEVICE_NAME (" | cut -d "(" -f2 | cut -d ")" -f1)
        open -Fn "$(xcode-select -p)/Applications/Simulator.app"
        xcrun simctl bootstatus $target_sim_id -b
      name: Preboot Simulator

    - run: npm run e2e-test
      name: Run functional tests
